[features]
seeds = false
skip-lint = false

[programs.localnet]
stablecoin = "22txojBd5nbZtHsvfCkCAzV9RQmFC3kT8ziK2ZPozKRP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/anjola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.30.1"
solana_version = "1.17.0"
